### ISSUE TITLE
Deploy to staging

### ISSUE THREAD

**Issue by TacticallyCreative** [thisbythem/stag#10]
Hi all, loving Stag!

One thing I can't work out though: when configuring servers such as 'staging' and 'production', is there a way to specify that the "master" branch is deployed to 'production', while another branch such as "testing" is deployed to 'staging'?

I'm guessing this is potentially something that Stag can't do at the moment, but feel it would be a nice feature to add. Would allow teams to play with new ideas/features and add them to a staging area for review by the client without impacting any work going on with the master branch.

Loving your work of Stag, it's one of the best beta tools I've ever come across. It's been a breath of fresh air for my deployment strategy!

Cheers,

Jamie.

**Comment by nobodyiscertain** [comment]
Hi Jamie,

Thanks for the kind words, I'm glad to hear Stag has been working out for you!

Yes, currently Stag is only able to deploy the master branch. We've recently run into an issue where it'd be helpful for it to deploy a different branch as well, so that's on the horizon to make happen. I'll leave this issue open so I can notify you when it's been completed.

**Comment by TacticallyCreative** [comment]
Cheers Jamie. Nice to know we're thinking along the same lines! Look forward to it, and all the best!
